export const NotificationTypes = Object.freeze({
  MORNING_PROTOCOL_READY: "MORNING_PROTOCOL_READY",
  MORNING_PROTOCOL_PENDING: "MORNING_PROTOCOL_PENDING",
  NIGHT_PROTOCOL_READY: "NIGHT_PROTOCOL_READY",
  NIGHT_PROTOCOL_PENDING: "NIGHT_PROTOCOL_PENDING",
  CHALLENGE_DAY_READY: "CHALLENGE_DAY_READY",
  CHALLENGE_DAY_PENDING: "CHALLENGE_DAY_PENDING",
  CHALLENGE_DAY_COMPLETE: "CHALLENGE_DAY_COMPLETE",
  CHALLENGE_COMPLETE: "CHALLENGE_COMPLETE",
  STREAK_MILESTONE: "STREAK_MILESTONE",
  STREAK_AT_RISK: "STREAK_AT_RISK",
  JOURNAL_REMINDER: "JOURNAL_REMINDER",
  WEEKLY_INSIGHT_READY: "WEEKLY_INSIGHT_READY",
  ACHIEVEMENT_UNLOCKED: "ACHIEVEMENT_UNLOCKED",
  SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",
});

export const NotificationSkipReasons = Object.freeze({
  ALREADY_COMPLETED: "ALREADY_COMPLETED",
  PREFERENCE_DISABLED: "PREFERENCE_DISABLED",
  NO_ACTIVE_CHALLENGE: "NO_ACTIVE_CHALLENGE",
  NO_VALID_TOKEN: "NO_VALID_TOKEN",
  QUIET_HOURS: "QUIET_HOURS",
  DUPLICATE: "DUPLICATE",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_DUE: "NOT_DUE",
});
